### ISSUE TITLE
Special characters are broken.

### ISSUE THREAD

**Issue by shlee625** [gkeep/iceberg-dark#2]
Hello.
Thanks for your fancy work! Looks really nice and I'm really enjoying your work.
But when I run a tmux session, special characters in the tmux status bar looks broken.
I'm using powerline fonts and here's a screenshot. Thanks.
<img width="1118" alt="Screen Shot 2019-10-17 at 11 09 52 PM" src="https://user-images.githubusercontent.com/46414706/67016535-497bff80-f133-11e9-8dc3-7b04dc3a4925.png">

**Comment by gkeep** [comment]
That's weird. Can you provide what terminal emulator and font you are using?

**Comment by shlee625** [comment]
> That's weird. Can you provide what terminal emulator and font you are using?

Sure thing. I use iTerm2 v3.3.5 on OS X 10.14.5 and the tmux version is 2.9a.
I tried two fonts: 'Hack', and 'Droid Sans Mono for Powerline'.
Only two extra lines are added to your iceberg.tmux.conf to enable 256 colors:
```
set -g terminal-overrides ",xterm-256color:Tc"
set -g default-terminal "screen-256color" 
```

**Comment by gkeep** [comment]
I think the problem is in the font. Can you try one of [nerd fonts](https://github.com/ryanoasis/nerd-fonts/#patched-fonts)? There are both Hack and Droid Sans Mono variants.

**Comment by shlee625** [comment]
> I think the problem is in the font. Can you try one of [nerd fonts](https://github.com/ryanoasis/nerd-fonts/#patched-fonts)? There is both Hack and Droid Sans Mono variants.

Great! Thanks for your help. The problem has been solved.
By the way, it would be great if you add this issue to README.md to let people know.
Thank you again for this nice work!

**Comment by gkeep** [comment]
Yes, I'm already on it. Thanks for using!
