### ISSUE TITLE
Tmux config example

### ISSUE THREAD

**Issue by spyroot** [gkeep/iceberg-dark#3]
I I think you should indicate in doc what setting goes where.
it super unclear.

**Comment by gkeep** [comment]
Not sure I follow. Are you talking about the tmux theme with powerline symbols?

**Comment by spyroot** [comment]
I figure out but full config would help.  I noticed that order matters if you have source powerline for example do you need to add iceberg_minim.  if you do before it doesn't work.  I guess if you put an example folder and tmux for a screenshot that you have.  Thank you fo the work.

**Comment by gkeep** [comment]
Ah, that makes sense. I’ll see what I can do. Can’t give an ETA just yet. 

Meanwhile, you can use my [tmux config](https://github.com/gkeep/dotfiles/blob/master/.tmux.conf) as an example.
